name: Run Unit Tests

on:
  push:
    paths:
      - 'packages/server/**'

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm --filter "./packages/server" install
      - run: pnpm --filter "./packages/server" test